<?php
/**
 *  * Template Name: 前台显示所有插件页
 *   *
 *    * @package WordPress
 *     * @subpackage Twenty_Fourteen
 *      * @since Twenty Fourteen 1.0
 *       */
require_once(ABSPATH . 'wp-admin/includes/plugin.php');
$plugins = get_plugins();//所有插件
$active_plugins = get_option('active_plugins');//启动的插件名称
//返回启动的插件详细信息
//function myfilter($plugins,$active){
//    $show_plugins = array();
//        foreach ($plugins as $k=>$v) {
//                if(in_array($k,$active)){
//                            $show_plugins[$k] = $v;
//                                    }
//                                        }
//                                            return $show_plugins;
//                                            }
//                                            $show_plugins = myfilter($plugins,$active_plugins);
//                                            get_header();
//                                            ?>
//
//                                                <div id="main-content" class="main-content">
//
//                                                        <div id="primary" class="content-area">
//                                                                    <div id="content" class="site-content" role="main">
//
//                                                                                    <article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
//                                                                                                        <?php
//                                                                                                                                the_title( '<header class="entry-header"><h1 class="entry-title">', '</h1></header>' );
//                                                                                                                                                    ?>
//
//                                                                                                                                                                        <div class="entry-content">
//                                                                                                                                                                                                <?php
//                                                                                                                                                                                                                            //显示自定义页编辑器输入的内容
//                                                                                                                                                                                                                                                        while ( have_posts() ) : the_post();
//                                                                                                                                                                                                                                                                                        the_content();
//                                                                                                                                                                                                                                                                                                                    endwhile;
//                                                                                                                                                                                                                                                                                                                                            ?>
//                                                                                                                                                                                                                                                                                                                                                                    <?php foreach ($show_plugins as $plugin) :?>
//                                                                                                                                                                                                                                                                                                                                                                                                <h3><?= $plugin['Title'] ?>(Version:<?= $plugin['Version'] ?>)</h3>
//                                                                                                                                                                                                                                                                                                                                                                                                                            <li>描述：<?= strip_tags($plugin['Description']) ?></li>
//                                                                                                                                                                                                                                                                                                                                                                                                                                                        <li>作者：<?= $plugin['Author'] ?></li>
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <li>作者主页：<a href="<?= $plugin['AuthorURI'] ?>" target="_blank" rel="nofollow"><?= $plugin['AuthorURI'] ?></a></li>
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <?php endforeach; ?>
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div><!-- .entry-content -->
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </article><!-- #post-## -->
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // If comments are open or we have at least one comment, load up the comment template.
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if ( comments_open() || get_comments_number() ) {
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                comments_template();
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ?>
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div><!-- #content -->
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div><!-- #primary -->
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php get_sidebar( 'content' ); ?>
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div><!-- #main-content -->
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    get_sidebar();
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    get_footer();
